# Generated by Django 4.1.3 on 2022-12-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='메일주소'),
        ),
    ]
