# Generated by Django 4.1.3 on 2022-12-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered_dttm',
            field=models.DateField(auto_now_add=True, verbose_name='등록시간'),
        ),
    ]
